package com.company;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Color;
import org.golchin.Line;
import java.awt.Dimension;

public class MyDrawing extends JFrame {
    private JPanel jPanel = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            ((Graphics2D) g).setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g.setColor(Color.black);
            g.drawRect(0, 0, 100, 100);
            {
                Line line = new Line(100, 200, Color.WHITE);
                line.drawInto("file.png");
                g.setColor(Color.red);
                g.drawOval(0, 0, 600, 600);
            }
        }
    };
    public static void main(String[] args) {
        MyDrawing canvas = new MyDrawing();
        canvas.initialize();
    }

    public void initialize() {
        setTitle("MyDrawing");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        add(jPanel);
        jPanel.setPreferredSize(new Dimension(500, 500));
        pack();
        setVisible(true);
    }
}
